version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - .:/home/app
  mysql-db:
    image: mysql:8.0.30-debian
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: med_record_db
    ports:
      - 3306:3306
    volumes:
      - /home/victor/docker_volumes/mysql:/var/lib/mysql
