apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: med-record-tls
  namespace: med-record-dev
spec:
  secretName: med-record-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: med-record.goncalvesmarques.com
  dnsNames:
    - med-record.goncalvesmarques.com
