apiVersion: apps/v1
kind: Deployment
metadata:
  name: med-record
  namespace: med-record-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: med-record
  template:
    metadata:
      labels:
        app: med-record
    spec:
      initContainers:
        - name: migrate
          image: vgmarques/med-record
          command: ["npx", "prisma", "migrate", "deploy"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: med-record-secret
                  key: DATABASE_URL
      containers:
        - name: med-record
          image: vgmarques/med-record
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: med-record-secret
                  key: DATABASE_URL
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          envFrom:
            - configMapRef:
                name: med-record-configmap
