apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: med-record-hpa
  namespace: med-record-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    name: med-record
    kind: Deployment
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 75
