name: CD - Deploy to Production

on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: prod
      APP_PORT: "3000"
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN }}
      JWT_ALGORITHM: ${{ secrets.JWT_ALGORITHM }}
    services:
      mysql:
        image: mysql:8.0.30-debian
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: med_record_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.14.0

      - name: Install dependencies
        run: npm install

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Migrate Database
        run: npx prisma migrate deploy

      - name: Executar Testes e Gerar Cobertura
        run: npm run test:coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          repository: ${{ secrets.DOCKER_USERNAME }}/med-record
          tags: ${{ secrets.DOCKER_USERNAME }}/med-record:${{ github.sha }},${{ secrets.DOCKER_USERNAME }}/med-record:latest

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: "4.1.3"

      - name: Update Kubernetes resources
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          cd k8s
          kustomize edit set image $DOCKER_USERNAME/med-record=$DOCKER_USERNAME/med-record:${{ github.sha }}
      - name: Commit
        run: |
          git config --global user.email "action@github.com"
          git config --local user.name "GitHub Action"	
          git commit -am "Update image to $DOCKER_USERNAME/med-record:${{ github.sha }}"
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
