name: CDGitops

on:
  push:
    branches: [develop]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.14.0

      - name: Instalar Dependências
        run: npm install

      - name: Executar Lint
        run: npm run lint

      - name: Executar Testes
        run: npm test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          repository: ${{ secrets.DOCKER_USERNAME }}/med-record
          tags: ${{ secrets.DOCKER_USERNAME }}/med-record:${{ github.sha }},${{ secrets.DOCKER_USERNAME }}/med-record:latest

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: "4.1.3"

      - name: Update Kubernetes resources
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          cd k8s
          kustomize edit set image $DOCKER_USERNAME/med-record=$DOCKER_USERNAME/med-record:${{ github.sha }}
      - name: Commit
        run: |
          git config --global user.email "action@github.com"
          git config --local user.name "GitHub Action"	
          git commit -am "Update image to $DOCKER_USERNAME/med-record:${{ github.sha }}"
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: develop
