name: ci-node-pre-push

on:
  pull_request:
    branches:
      - develop

jobs:
  check-application:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
      APP_PORT: "3000"
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN }}
      JWT_ALGORITHM: ${{ secrets.JWT_ALGORITHM }}

    services:
      mysql:
        image: mysql:8.0.30-debian
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: med_record_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.14.0"

      - name: Install dependencies
        run: npm install

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Migrate Database
        run: npx prisma migrate deploy

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm run test
